// <auto-generated />
using CraftingCalculator.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CraftingCalculator.Infrastructure.Migrations
{
    [DbContext(typeof(CraftingDataContext))]
    [Migration("20260909182043_AddComponentCategory")]
    partial class AddComponentCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.Blueprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductionTime")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.Property<long>("Yield")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Blueprints", (string)null);
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.BlueprintChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildBlueprintId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentBlueprintId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChildBlueprintId");

                    b.HasIndex("ParentBlueprintId");

                    b.ToTable("BlueprintChildren", (string)null);
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.BlueprintComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlueprintId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId");

                    b.HasIndex("ComponentId");

                    b.ToTable("BlueprintComponents", (string)null);
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductionTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Components", (string)null);
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Favorites", (string)null);
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.FavoriteBlueprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlueprintId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FavoriteId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId");

                    b.HasIndex("FavoriteId");

                    b.ToTable("FavoriteBlueprints", (string)null);
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.Blueprint", b =>
                {
                    b.HasOne("CraftingCalculator.Domain.Entities.Category", "Category")
                        .WithMany("Blueprints")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.BlueprintChild", b =>
                {
                    b.HasOne("CraftingCalculator.Domain.Entities.Blueprint", "Child")
                        .WithMany("ParentLinks")
                        .HasForeignKey("ChildBlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftingCalculator.Domain.Entities.Blueprint", "ParentBlueprint")
                        .WithMany("Children")
                        .HasForeignKey("ParentBlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("ParentBlueprint");
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.BlueprintComponent", b =>
                {
                    b.HasOne("CraftingCalculator.Domain.Entities.Blueprint", "Blueprint")
                        .WithMany("Components")
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftingCalculator.Domain.Entities.Component", "Component")
                        .WithMany("BlueprintComponents")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blueprint");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.Component", b =>
                {
                    b.HasOne("CraftingCalculator.Domain.Entities.Category", "Category")
                        .WithMany("Components")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.FavoriteBlueprint", b =>
                {
                    b.HasOne("CraftingCalculator.Domain.Entities.Blueprint", "Blueprint")
                        .WithMany("FavoriteBlueprints")
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftingCalculator.Domain.Entities.Favorite", "Favorite")
                        .WithMany("FavoriteBlueprints")
                        .HasForeignKey("FavoriteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blueprint");

                    b.Navigation("Favorite");
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.Blueprint", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Components");

                    b.Navigation("FavoriteBlueprints");

                    b.Navigation("ParentLinks");
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.Category", b =>
                {
                    b.Navigation("Blueprints");

                    b.Navigation("Components");
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.Component", b =>
                {
                    b.Navigation("BlueprintComponents");
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.Favorite", b =>
                {
                    b.Navigation("FavoriteBlueprints");
                });
#pragma warning restore 612, 618
        }
    }
}
