// <auto-generated />
using CraftingCalculator.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CraftingCalculator.Infrastructure.Migrations
{
    [DbContext(typeof(CraftingDataContext))]
    partial class CraftingDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Favorites", (string)null);
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.FavoriteRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FavoriteId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteId");

                    b.HasIndex("RecipeId");

                    b.ToTable("FavoriteRecipes", (string)null);
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Ingredients", (string)null);
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FilterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FilterId");

                    b.HasIndex("Name");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.RecipeChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChildRecipeId");

                    b.HasIndex("ParentRecipeId");

                    b.ToTable("RecipeChildren", (string)null);
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.RecipeFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("RecipeFilters", (string)null);
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients", (string)null);
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.FavoriteRecipe", b =>
                {
                    b.HasOne("CraftingCalculator.Domain.Entities.Favorite", "Favorite")
                        .WithMany("FavoriteRecipes")
                        .HasForeignKey("FavoriteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftingCalculator.Domain.Entities.Recipe", "Recipe")
                        .WithMany("FavoriteRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Favorite");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("CraftingCalculator.Domain.Entities.RecipeFilter", "Filter")
                        .WithMany("Recipes")
                        .HasForeignKey("FilterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Filter");
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.RecipeChild", b =>
                {
                    b.HasOne("CraftingCalculator.Domain.Entities.Recipe", "Child")
                        .WithMany("ParentLinks")
                        .HasForeignKey("ChildRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftingCalculator.Domain.Entities.Recipe", "ParentRecipe")
                        .WithMany("Children")
                        .HasForeignKey("ParentRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("ParentRecipe");
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("CraftingCalculator.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftingCalculator.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.Favorite", b =>
                {
                    b.Navigation("FavoriteRecipes");
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("FavoriteRecipes");

                    b.Navigation("Ingredients");

                    b.Navigation("ParentLinks");
                });

            modelBuilder.Entity("CraftingCalculator.Domain.Entities.RecipeFilter", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
